-- Migración: módulo de Rutas de Vibración
-- Ejecutar en SQL Editor de Supabase.

CREATE TABLE IF NOT EXISTS rutas_vibracion (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  unidad TEXT NOT NULL,
  frecuencia TEXT NOT NULL,
  nro_plan TEXT,
  activa BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ruta_equipos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ruta_id UUID REFERENCES rutas_vibracion(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  ubicacion_tecnica TEXT,
  unidad TEXT,
  equipo_id UUID,
  orden INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(ruta_id, nombre)
);

CREATE TABLE IF NOT EXISTS ruta_ejecuciones (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ruta_id UUID REFERENCES rutas_vibracion(id),
  orden_trabajo TEXT,
  fecha_inicio DATE DEFAULT CURRENT_DATE,
  fecha_cierre DATE,
  estado TEXT DEFAULT 'en_progreso',
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ruta_ejecucion_equipos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ejecucion_id UUID REFERENCES ruta_ejecuciones(id) ON DELETE CASCADE,
  ruta_equipo_id UUID REFERENCES ruta_equipos(id),
  completado BOOLEAN DEFAULT false,
  observacion TEXT,
  completado_at TIMESTAMPTZ,
  completado_by UUID,
  UNIQUE(ejecucion_id, ruta_equipo_id)
);

-- Seed de rutas y equipos
INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U1 15D', 'U1', '2S', '5000083260') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -1A', '2893-12-LAC01-AP101-MG01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -1B', '2893-12-LAC01-AP102-MG01', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -1C', '2893-12-LAC01-AP103-MG01', 'U1', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION PRINCIPAL B.A.A 1A', '2893-12-LAC01-AP101-KP03', 'U1', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION PRINCIPAL B.A.A 1B', '2893-12-LAC01-AP102-KP03', 'U1', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION PRINCIPAL B.A.A 1C', '2893-12-LAC01-AP103-KP03', 'U1', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION AUXILIAR B.A.A 1C', '2893-12-LAC01-AP103-KP02', 'U1', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -1A', '2893-12-LCB01-AP101-KP01', 'U1', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -1B', '2893-12-LCB01-AP102-KP01', 'U1', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -1A', '2893-13-PAC01-AP101-KP01', 'U1', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -1B', '2893-13-PAC01-AP102-KP01', 'U1', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO TURBINA U1 15D', 'U1', '2S', '5000083261') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SISTEMA TURBINA U1', '2893-11-MAB', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'DESCANSOS GENERADOR U1', '2893-11-MAK20-AE401', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U1 15D', 'U1', '2S', '5000083262') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U1', '2893-15-HLB40-AN101-KN01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PRIMARIO VAP U1', '2893-15-HLB20-AN101--M01', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR GASES RECIRCULACION VRG U1', '2893-15-HNF01-AN101--M01', 'U1', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'UNIDAD VENTILADOR VTI U1', '2893-15-HTC02-AN101--M01', 'U1', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO FORZADO VTF U1', '2893-15-HLB10-AN101--M01', 'U1', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U2 15D', 'U2', '2S', '5000083269') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -2A', '2893-22-LAC01-AP101-KP01', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -2B', '2893-22-LAC01-AP102-KP01', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -2C', '2893-22-LAC01-AP103-KP01', 'U2', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION AUXILIAR B.A.A 2A', '2893-22-LAC01-AP101-KP02', 'U2', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION AUXILIAR B.A.A 2B', '2893-22-LAC01-AP102-KP02', 'U2', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION AUXILIAR B.A.A 2C', '2893-22-LAC01-AP103-KP02', 'U2', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -2A', '2893-22-LCB01-AP101-KP01', 'U2', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -2B', '2893-22-LCB01-AP102-KP01', 'U2', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -2A', '2893-23-PAC01-AP101-KP01', 'U2', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -2B', '2893-23-PAC01-AP102-KP01', 'U2', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -2A', '2893-23-PAD01-AP101-KP01', 'U2', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -2B', '2893-23-PAD01-AP102-KP01', 'U2', 11 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO TURBINA U2 15D', 'U2', '2S', '5000083270') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SISTEMA TURBINA U2', '2893-21-MAB', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'DESCANSOS GENERADOR U2', '2893-21-MAK20-AE401', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U2 15D', 'U2', '2S', '5000083271') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U2', '2893-25-HLB40-AN101-MU02', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PRIMARIO VAP U2', '2893-25-HLB20-AN101--M01', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR GASES RECIRCULACION VRG U2', '2893-25-HNF01-AN101--M01', 'U2', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'UNIDAD VENTILADOR VTI U2', '2893-25-HTC02-AN101--M01', 'U2', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO FORZADO VTF U2', '2893-25-HLB10-AN101--M01', 'U2', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U3 15D', 'U3', '2S', '5000083278') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -3A', '2893-32-LAC01-AP101-KP01', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -3B', '2893-32-LAC01-AP102-KP01', 'U3', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -3C', '2893-32-LAC01-AP103-KP01', 'U3', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -A B.A.A 3A', '2893-32-LAC01-AP101-KP02', 'U3', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -B B.A.A 3A', '2893-32-LAC01-AP101-KP03', 'U3', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -A B.A.A 3B', '2893-32-LAC01-AP102-KP02', 'U3', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -B B.A.A 3B', '2893-32-LAC01-AP102-KP03', 'U3', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -3A', '2893-32-LCB01-AP101-KP01', 'U3', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -3B', '2893-32-LCB01-AP102-KP01', 'U3', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -3A', '2893-33-PAC01-AP101-KP01', 'U3', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -3B', '2893-33-PAC01-AP102-KP01', 'U3', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -3A', '2893-33-PAD01-AP101-KP02', 'U3', 11 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -3B', '2893-33-PAD01-AP102-KP02', 'U3', 12 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO TURBINA U3 15D', 'U3', '2S', '5000083279') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SISTEMA TURBINA U3', '2893-31-MAB', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'DESCANSOS GENERADOR U3', '2893-31-MAK20-AE401', 'U3', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U3 15D', 'U3', '2S', '5000083280') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U3', '2893-35-HLB40-AN101--M01', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PRIMARIO VAP U3', '2893-35-HLB20-AN101--M01', 'U3', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR GASES RECIRCULACION VRG U3', '2893-35-HNF01-AN101--M01', 'U3', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO INDUCIDO VTI U3', '2893-35-HNC01-AN101--M01', 'U3', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO FORZADO VTF U3', '2893-35-HLB10-AN101--M01', 'U3', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U4 15D', 'U4', '2S', '5000083287') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -4A', '2893-42-LAC01-AP101-MU01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -4B', '2893-42-LAC01-AP102-MU01', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -A (B.A.A 4A)', '2893-42-LAC01-AP101-KP02', 'U4', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -B (B.A.A 4A)', '2893-42-LAC01-AP101-KP03', 'U4', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA LUBRICACION -B (B.A.A 4B)', '2893-42-LAC01-AP102-KP03', 'U4', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -4A', '2893-42-LCB01-AP101-KP01', 'U4', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -4B', '2893-42-LCB01-AP102--M01', 'U4', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -4A', '2893-43-PAC01-AP101--M01', 'U4', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -4B', '2893-43-PAC01-AP102--M01', 'U4', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -4A', '2893-43-PAD01-AP101--M01', 'U4', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -4B', '2893-43-PAD01-AP102--M01', 'U4', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO TURBINA U4 15D', 'U4', '2S', '5000083288') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SISTEMA TURBINA U4', '2893-41-MAB', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'DESCANSOS GENERADOR U4', '2893-41-MAK20-AE401', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U4 15D', 'U4', '2S', '5000083289') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U4', '2893-45-HLB40-AN101--M01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PRIMARIO VAP U4', '2893-45-HLB20-AN101--M01', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR GASES RECIRCULACION VRG U4', '2893-45-HNF01-AN101--M01', 'U4', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'UNIDAD VENTILADOR VTI U4', '2893-45-HTC02-AN101--M01', 'U4', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO FORZADO VTF U4', '2893-45-HLB10-AN101--M01', 'U4', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U5 15D', 'U5', '2S', '5000083296') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -5A', '2893-52-LAC01-AP101--M03', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -5B', '2893-52-LAC01-AP102--M03', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ALIMENTACION -5C', '2893-52-LAC01-AP103--M03', 'U5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -5A', '2893-52-LCB01-AP101--M01', 'U5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA CONDENSADA -5B', '2893-52-LCB01-AP102--M01', 'U5', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -5A', '2893-53-PAC01-AP101-KP01', 'U5', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION PRINCIPAL -5B', '2893-53-PAC01-AP102-KP01', 'U5', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO TURBINA U5 15D', 'U5', '2S', '5000083297') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SISTEMA TURBINA U5', '2893-51-MAB', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'DESCANSOS GENERADOR U5', '2893-51-MAK20-AE401', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO TURBINA U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U5 15D', 'U5', '2S', '5000083298') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PRIMARIO VAP U5', '2893-55-HLB20-AN101--M01', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR GASES RECIRCULACION VRG U5', '2893-55-HNF01-AN101--M01', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO FORZADO VTF U5', '2893-55-HLB10-AN101--M01', 'U5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR TIRO INDUCIDO VTI U5', '2893-55-HNC01-AN101--M01', 'U5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MOTOR VAI U5', '2893-55-HLB40-AN101--M01', 'U5', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5 15D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM SISTEMAS COMUNES  BOMBAS PRETRA 90D', 'SC', '3M', '5000083306') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PRETRATADA -A U1-2', '2893-01-GAD12-AP101--M01', 'SC', 0 FROM rutas_vibracion WHERE nombre = 'MP MM SISTEMAS COMUNES  BOMBAS PRETRA 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PRETRATADA -B U1-2', '2893-01-GAD12-AP102--M01', 'SC', 1 FROM rutas_vibracion WHERE nombre = 'MP MM SISTEMAS COMUNES  BOMBAS PRETRA 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PRETRATADA -C U1-2', '2893-01-GAD12-AP103-KP01', 'SC', 2 FROM rutas_vibracion WHERE nombre = 'MP MM SISTEMAS COMUNES  BOMBAS PRETRA 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MM MONITOREO BOMBAS RETROFIT 90D', 'SC', '3M', '5000083308') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA HUMECTACION -1 HTQ41AP001', '2893-01-GDL12-AP101--M01', 'SC', 0 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA HUMECTACION -2 HTQ42AP001', '2893-01-GDL12-AP102--M01', 'SC', 1 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PROCESO U1 01HTQ15AP001', '2893-01-GDL14-AP101--M01', 'SC', 2 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PROCESO U2 02HTQ15AP001', '2893-01-GDL14-AP102--M01', 'SC', 3 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA PROCESO U4 04HTQ15AP001', '2893-01-GDL14-AP104--M01', 'SC', 4 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA HIDRATACION -1 HTQ37AP001', '2893-01-HTJ02-AP001--M01', 'SC', 5 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA HIDRATACION -2 HTQ38AP001', '2893-01-HTJ02-AP002--M01', 'SC', 6 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA DE TORNILLO -1 HTP13AP001', '2893-15-HTL02-AP102--M01', 'SC', 7 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA DE TORNILLO -2 HTP23AP001', '2893-25-HTL02-AP103--M01', 'SC', 8 FROM rutas_vibracion WHERE nombre = 'MM MONITOREO BOMBAS RETROFIT 90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U1  90 D', 'U1', '3M', '5000083264') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -1A', '2893-13-PAD01-AP101--M01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA CIRCULACION AUXILIAR -1B', '2893-13-PAD01-AP102--M01', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -1A', '2893-13-PAD04-AP101--M01', 'U1', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -1B', '2893-13-PAD04-AP102--M01', 'U1', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -1A', '2893-13-PGH01-AP101--M01', 'U1', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -1B', '2893-13-PGH01-AP102--M01', 'U1', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U1  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U2  90 D', 'U2', '3M', '5000083273') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -2A', '2893-23-PAD04-AP101--M01', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -2B', '2893-23-PAD04-AP102--M01', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -2A', '2893-23-PGH01-AP101--M01', 'U2', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -2B', '2893-23-PGH01-AP102--M01', 'U2', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U2  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U4  90 D', 'U4', '3M', '5000083291') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -4A', '2893-43-PAD04-AP101--M01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -4B', '2893-43-PAD04-AP102--M01', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -4A', '2893-43-PGH01-AP101--M01', 'U4', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -4B', '2893-43-PGH01-AP102--M01', 'U4', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U4  90 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CAR U1  90D', 'U1', '3M', '5000083266') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CALENTADOR AIRE REGENERATIVO U1', '2893-15-HLD20-AC101--M01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CAR U1  90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CAR U2  90D', 'U2', '3M', '5000083275') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CALENTADOR AIRE REGENERATIVO U2', '2893-25-HLD20-AC101--M01', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CAR U2  90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CAR U3  90D', 'U3', '3M', '5000083284') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CALENTADOR AIRE REGENERATIVO U3', '2893-35-HLD20-AC101--M01', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CAR U3  90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CAR U4  90D', 'U4', '3M', '5000083293') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CALENTADOR AIRE REGENERATIVO U4', '2893-45-HLD20-AC101--M01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CAR U4  90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CAR U5  90D', 'U5', '3M', '5000083303') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CALENTADOR AIRE REGENERATIVO U4', '2893-55-HLD20-AC101--M02', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CAR U5  90D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U3  180D', 'U1-2', '6M', '5000083282') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA PETROLEO DIESEL -A U1-2', '2893-01-EGE03-AP101--M01', 'U1-2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA PETROLEO DIESEL -B U1-2', '2893-01-EGE03-AP102--M01', 'U1-2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA PETROLEO DIESEL -A U3-4-5', '2893-01-EGE04-AP101--M01', 'U3-4-5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA PETROLEO DIESEL -B U3-4-5', '2893-01-EGE04-AP102--M01', 'U3-4-5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -4A', '2893-33-PAD04-AP101--M01', 'U3', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -3B', '2893-33-PAD04-AP102--M01', 'U3', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -A', '2893-33-PGH01-AP101--M01', 'U3', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -B', '2893-33-PGH01-AP102--M01', 'U3', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA YESO (CEBADO) A', '2893-35-HRA01-AP101--M01', 'U3', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA YESO (CEBADO) B', '2893-35-HRA01-AP102--M01', 'U3', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA RECIRCULACION ABSORBER -B', '2893-35-HRA05-AP102--M01', 'U3', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELIMINADOR NIEBLA -A', '2893-35-HRA07-AP101--M01', 'U3', 11 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELIMINADOR NIEBLA -B', '2893-35-HRA07-AP102--M01', 'U3', 12 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA DE VACIO FILTRO BANDA A', '2893-35-HRB02-AP101--M01', 'U3', 13 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA DE VACIO FILTRO BANDA B', '2893-35-HRB03-AP101--M01', 'U3', 14 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA FILTRADO -A', '2893-35-HRB04-AP102--M01', 'U3', 15 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA FILTRADO -B', '2893-35-HRB04-AP202--M01', 'U3', 16 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBAS RECICLADO -B', '2893-35-HRD02-AP102--M01', 'U3', 17 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U3  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO BOMBAS U5  180D', 'U5', '6M', '5000083300') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -5A', '2893-53-PAD04-AP101--M01', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA BOOSTER -5B', '2893-53-PAD04-AP102--M01', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -5A', '2893-53-PGH01-AP101--M01', 'U5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA AGUA ENFRIAMIENTO -5B', '2893-53-PGH01-AP102--M01', 'U5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA YESO (CEBADO) 5A', '2893-55-HRA01-AP101--M01', 'U5', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA YESO (CEBADO) 5B', '2893-55-HRA01-AP102--M01', 'U5', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELIMINADOR NIEBLA -5A', '2893-55-HRA07-AP101--M01', 'U5', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELIMINADOR NIEBLA -5B', '2893-55-HRA07-AP102--M01', 'U5', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ALIMENTACION LECHADA 5A', '2893-55-HRD03-AP101--M01', 'U5', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ALIMENTACION LECHADA 5B', '2893-55-HRD03-AP102--M01', 'U5', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO BOMBAS U5  180D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO ESCORIA U1  180 D', 'U1', 'U1', '5000083265') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CADENA SUMERGIDA U1', '2893-16-ETA01-AT101--M01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U1  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -1 ESCORIA U1', '2893-16-ETA02-AF101--M01', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U1  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -2 ESCORIA U1', '2893-16-ETA02-AF102--M01', 'U1', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U1  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRITURADOR DE ESCORIA U1', '2893-16-ETA01-AJ101--M01', 'U1', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U1  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA VACIO -1B', '2893-16-ETG08-AP202', 'U1', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U1  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO ESCORIA U2  180 D', 'U2', '6M', '5000083274') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CADENA SUMERGIDA U2', '2893-26-ETA01-AT101--M01', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U2  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -1 ESCORIA U2', '2893-26-ETA02-AF101--M01', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U2  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -2 ESCORIA U2', '2893-26-ETA02-AF102--M01', 'U2', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U2  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRITURADOR DE ESCORIA U2', '2893-26-ETA01-AJ101--M01', 'U2', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U2  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA VACIO 2B', '2893-26-ETG08-AP202', 'U2', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U2  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO ESCORIA U3  180 D', 'U3', '6M', '5000083283') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CADENA SUMERGIDA U3', '2893-36-ETA01-AT101--M01', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U3  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA ALIM CALIZA AL MOLINO DE MARTILLO U3', '2893-35-HRD01-AF101--M01', 'U3', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U3  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -1 ESCORIA U3', '2893-36-ETA02-AF101--M01', 'U3', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U3  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -2 ESCORIA U3', '2893-36-ETA02-AF102--M01', 'U3', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U3  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRITURADOR DE ESCORIA U3', '2893-36-ETA01-AJ101--M01', 'U3', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U3  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO ESCORIA U4  180 D', 'U4', '6M', '5000083292') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CADENA SUMERGIDA U4', '2893-46-ETA01-AT101--M01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U4  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -1 ESCORIA U4', '2893-46-ETA02-AF101--M01', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U4  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -2 ESCORIA U4', '2893-46-ETA02-AF102--M01', 'U4', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U4  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRITURADOR DE ESCORIA U4', '2893-46-ETA01-AJ101--M01', 'U4', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U4  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO ESCORIA U5  180 D', 'U5', '6M', '5000083302') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CADENA SUMERGIDA U5', '2893-56-ETA01-AT101--M01', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U5  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -1 ESCORIA U5', '2893-56-ETA02-AF101--M01', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U5  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA -2 ESCORIA U5', '2893-56-ETA02-AF102--M01', 'U5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U5  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRITURADOR DE ESCORIA U5', '2893-56-ETA01-AJ101--M01', 'U5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO ESCORIA U5  180 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CONDICIONES LLENADO SILO', 'SMC', '1M', '5000083307') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C4/5', '2893-01-ECA02-AF003--M01', 'SMC', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C6B', '2893-01-ECA03-AF004--M01', 'SMC', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C7', '2893-01-ECA04-AF001--M01', 'SMC', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C8', '2893-01-ECA05-AF001--M01', 'SMC', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C9', '2893-01-ECA06-AF001--M01', 'SMC', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C10', '2893-01-ECA08-AF001--M01', 'SMC', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C11', '2893-01-ECA09-AF001--M01', 'SMC', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C12', '2893-01-ECA10-AF001--M01', 'SMC', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C13', '2893-01-ECA11-AF001--M01', 'SMC', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRIPPER U1U2', '2893-01-ECA17-AF001--M01', 'SMC', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRIPPER U3U4', '2893-01-ECA17-AF002--M01', 'SMC', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRIPPER U5', '2893-01-ECA17-AF003--M01', 'SMC', 11 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES LLENADO SILO' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO CONDICIONES PUERTO 30D', 'SMC', '1M', '5000083310') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO ELEVACION GRUA 1', '2893-01-EAA02-AU001--M01', 'SMC', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO CIERRE  GRUA 1', '2893-01-EAA02-AU002--M01', 'SMC', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO GIRO -A GRUA 1', '2893-01-EAA02-AU003--M01', 'SMC', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO GIRO -B GRUA 1', '2893-01-EAA02-AU003--M02', 'SMC', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO PLUMA GRUA 1', '2893-01-EAA02-AU004--M01', 'SMC', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO ELEVACION GRUA 2', '2893-01-EAA03-AU001--M01', 'SMC', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO CIERRE GRUA 2', '2893-01-EAA03-AU002--M01', 'SMC', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO GIRO -A GRUA 2', '2893-01-EAA03-AU003--M01', 'SMC', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO GIRO -B GRUA 2', '2893-01-EAA03-AU003--M02', 'SMC', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'MECANISMO PLUMA GRUA 2', '2893-01-EAA03-AU004--M01', 'SMC', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -B MOTOR C9-1', '2893-01-EAA06-AF001--M01', 'SMC', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -A MOTOR C9-1', '2893-01-EAA06-AF001--M02', 'SMC', 11 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -B MOTOR C9-2', '2893-01-EAA06-AF002--M01', 'SMC', 12 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -A MOTOR C9-2', '2893-01-EAA06-AF002--M02', 'SMC', 13 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -B MOTOR C9-3', '2893-01-EAA06-AF003--M01', 'SMC', 14 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VIBRADOR -A MOTOR C9-3', '2893-01-EAA06-AF003--M02', 'SMC', 15 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRANSPORTADOR 9-1', '2893-01-EAA07-AF001--M01', 'SMC', 16 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRANSPORTADOR 9-2', '2893-01-EAA07-AF002--M01', 'SMC', 17 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'TRANSPORTADOR 9-3', '2893-01-EAA07-AF003--M01', 'SMC', 18 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C1', '2893-01-EAA08-AF001--M01', 'SMC', 19 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C2', '2893-01-EAA09-AF001--M02', 'SMC', 20 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA C3', '2893-01-EAA10-AF001--M01', 'SMC', 21 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'CORREA TRANSPORTADORA APILADOR RADIAL', '2893-01-EAD01-AF001--M01', 'SMC', 22 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO CONDICIONES PUERTO 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM  PLANTA DE AGUAS COMPRESORES 30D', 'DESAL', '1M', '5000083312') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -1 (U1)', '2893-01-GAA01-AN101--M01', 'DESAL', 0 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -2 (U2)', '2893-01-GAA02-AN101--M01', 'DESAL', 1 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -3 (U3)', '2893-01-GAA03-AN101--M01', 'DESAL', 2 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -4 (U3)', '2893-01-GAA04-AN101--M01', 'DESAL', 3 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -5 (U4)', '2893-01-GAA05-AN101--M01', 'DESAL', 4 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -6 (U5)', '2893-01-GAA06-AN101--M01', 'DESAL', 5 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR DESALADORA -7 (U5)', '2893-01-GAA07-AN101--M01', 'DESAL', 6 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR GBG20AN001 DES8', '2893-01-GDB01-AN101--M01', 'DESAL', 7 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR GBG20AN001 DES9', '2893-01-GDB02-AN101--M01', 'DESAL', 8 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR GBG20AN001 DES10', '2893-01-GDB03-AN101--M01', 'DESAL', 9 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'COMPRESOR VAPOR GBG20AN001 DES11', '2893-01-GDB04-AN101--M01', 'DESAL', 10 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELECTRICA -A SCI', '2893-01-SGX01-AP101--M01', 'DESAL', 11 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA ELECTRICA -B SCI', '2893-01-SGX01-AP102--M01', 'DESAL', 12 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA DIESEL SCI', '2893-01-SGX01-AP201--M01', 'DESAL', 13 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'BOMBA JOCKEY', '2893-01-SGX01-AP202--M01', 'DESAL', 14 FROM rutas_vibracion WHERE nombre = 'MP MM  PLANTA DE AGUAS COMPRESORES 30D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U1  60 D', 'U1', '2M', '5000083263') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -1A', '2893-15-HLB30-AN101--M01', 'U1', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -1B', '2893-15-HLB31-AN101--M01', 'U1', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION -1 QEH05AN001 U1', '2893-15-HSD01-AN101--M01', 'U1', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION -2 QEH08AN001 U1', '2893-15-HSD01-AN102--M01', 'U1', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -1A', '2893-15-HLB50-AN101--M01', 'U1', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -1B', '2893-15-HLB51-AN101--M01', 'U1', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U1', '2893-15-HLB40-AN101--M01', 'U1', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U1  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U2  60 D', 'U2', '2M', '5000083272') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -2A', '2893-25-HLB30-AN101--M01', 'U2', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -2B', '2893-25-HLB31-AN101--M01', 'U2', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -2A', '2893-25-HLB50-AN101--M01', 'U2', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -2B', '2893-25-HLB51-AN101--M01', 'U2', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U2', '2893-25-HLB40-AN101--M01', 'U2', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U2  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U3  60 D', 'U3', '2M', '5000083281') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -3A', '2893-35-HLB30-AN101--M01', 'U3', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -3B', '2893-35-HLB31-AN101--M01', 'U3', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -3A', '2893-35-HLB50-AN101--M01', 'U3', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -3B', '2893-35-HLB51-AN101--M01', 'U3', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -3A FGD', '2893-35-HNC02-AN101--M01', 'U3', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -3B FGD', '2893-35-HNC03-AN101--M01', 'U3', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SOPLADOR AIRE PURGA CAMPO 3A', '2893-35-HNF02-BB101-KN01', 'U3', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'SOPLADOR AIRE PURGA CAMPO 3B', '2893-35-HNF02-BB102-KN01', 'U3', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U3', '2893-35-HLB40-AN101--M01', 'U3', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U3  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U4  60 D', 'U4', '2M', '5000083290') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -4A', '2893-45-HLB30-AN101--M01', 'U4', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -4B', '2893-45-HLB31-AN101--M01', 'U4', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION AMON -4A HSA02AN101', '2893-45-HSD01-AN101--M01', 'U4', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION AMON -4B HSA02AN102', '2893-45-HSD01-AN102--M01', 'U4', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -4A', '2893-45-HLB50-AN101--M01', 'U4', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -4B', '2893-45-HLB51-AN101--M01', 'U4', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U4', '2893-45-HLB40-AN101--M01', 'U4', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U4  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;

INSERT INTO rutas_vibracion (nombre, unidad, frecuencia, nro_plan) VALUES ('MP MM MONITOREO VENTILADORES U5  60 D', 'U5', '2M', '5000083299') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -5A', '2893-55-HLB30-AN101--M01', 'U5', 0 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -5B', '2893-55-HLB31-AN101--M01', 'U5', 1 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -5A', '2893-55-HLB50-AN101--M01', 'U5', 2 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DETECTOR LLAMA VDLL -5B', '2893-55-HLB51-AN101--M01', 'U5', 3 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -5A FGD', '2893-55-HNC02-AN101--M01', 'U5', 4 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE SELLO VAS -5B FGD', '2893-55-HNC03-AN101--M01', 'U5', 5 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PURGA 5A', '2893-55-HNF02-BB101-KN01', 'U5', 6 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE PURGA 5B', '2893-55-HNF02-BB102-KN01', 'U5', 7 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION AMON -5A HSA02AN101', '2893-55-HSD01-AN101--M01', 'U5', 8 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR DILUCION AMON -5B HSA02AN102', '2893-55-HSD01-AN102--M01', 'U5', 9 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
INSERT INTO ruta_equipos (ruta_id, nombre, ubicacion_tecnica, unidad, orden) SELECT id, 'VENTILADOR AIRE IGNITORES U5', '2893-55-HLB40-AN101--M01', 'U5', 10 FROM rutas_vibracion WHERE nombre = 'MP MM MONITOREO VENTILADORES U5  60 D' ON CONFLICT (ruta_id, nombre) DO NOTHING;
